apiVersion: v1
kind: Secret
metadata:
  name: pick-a-meet-secret
  namespace: pick-a-meet
type: Opaque
stringData:
  DATABASE_USER: pick_a_meet_app
  DATABASE_PASSWORD: CHANGE_ME_DATABASE_PASSWORD
  SESSION_SECRET_KEY: CHANGE_ME_TO_AT_LEAST_32_RANDOM_CHARACTERS
  ADMIN_CONSOLE_PASSWORD: CHANGE_ME_ADMIN_CONSOLE_PASSWORD
